In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("covid_toy.csv")

In [4]:
df.sample(5)

    age  gender  fever   cough       city has_covid
25   23    Male    NaN    Mild     Mumbai        No
61   81  Female   98.0  Strong     Mumbai        No
35   82  Female  102.0  Strong  Bangalore        No
78   11    Male  100.0    Mild  Bangalore       Yes
92   82  Female  102.0  Strong    Kolkata        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [7]:
X_train, X_test,Y_train, Y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [9]:
X_train

    age  gender  fever   cough       city
75    5    Male  102.0    Mild    Kolkata
32   34  Female  101.0  Strong      Delhi
59    6  Female  104.0    Mild    Kolkata
36   38  Female  101.0    Mild  Bangalore
84   69  Female   98.0  Strong     Mumbai
..  ...     ...    ...     ...        ...
63   10    Male  100.0    Mild  Bangalore
46   19  Female  101.0    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
16   69  Female  103.0    Mild    Kolkata
3    31  Female   98.0    Mild    Kolkata

[80 rows x 5 columns]

# ColumnTransformer

In [10]:
from sklearn.compose import ColumnTransformer

In [19]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), #name,what to do, which columns
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough') #remianing column will remain as it is 'passthrough OR drop'

In [20]:
transformer.fit_transform(X_train).shape

(80, 7)

In [21]:
transformer.fit_transform(X_test).shape

(20, 7)