In [3]:
import pandas as pd

In [4]:
dataset = pd.read_csv("carsales.csv")
dataset.head(3)

    Make Colour  Odometer (KM)  Doors    Price
0  Honda  White        35431.0    4.0  15323.0
1    BMW   Blue       192714.0    5.0  19943.0
2  Honda  White        84714.0    4.0  28343.0

In [5]:
dataset.isnull().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [6]:
dataset["Colour"].fillna(dataset["Colour"].mode()[0], inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_99244\870378193.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Colour"].fillna(dataset["Colour"].mode()[0], inplace=True)

In [7]:
en_data = dataset[["Colour"]]
en_data

    Colour
0    White
1     Blue
2    White
3    White
4     Blue
..     ...
995  Black
996  White
997   Blue
998  White
999   Blue

[1000 rows x 1 columns]

In [8]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Colour_Black  1000 non-null   bool
 1   Colour_Blue   1000 non-null   bool
 2   Colour_Green  1000 non-null   bool
 3   Colour_Red    1000 non-null   bool
 4   Colour_White  1000 non-null   bool
dtypes: bool(5)
memory usage: 5.0 KB

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder() 
# ohe = OneHotEncoder(drop="first") drop first column of two categorical data like Gender_Male and Gender_Female it drops Gender_male
ar  = ohe.fit_transform(en_data).toarray()

In [11]:
pd.DataFrame(ar,columns=["Colour_Black","Colour_Blue","Colour_Green","Colour_Red","Colour_White"])

     Colour_Black  Colour_Blue  Colour_Green  Colour_Red  Colour_White
0             0.0          0.0           0.0         0.0           1.0
1             0.0          1.0           0.0         0.0           0.0
2             0.0          0.0           0.0         0.0           1.0
3             0.0          0.0           0.0         0.0           1.0
4             0.0          1.0           0.0         0.0           0.0
..            ...          ...           ...         ...           ...
995           1.0          0.0           0.0         0.0           0.0
996           0.0          0.0           0.0         0.0           1.0
997           0.0          1.0           0.0         0.0           0.0
998           0.0          0.0           0.0         0.0           1.0
999           0.0          1.0           0.0         0.0           0.0

[1000 rows x 5 columns]

In [13]:
dataset.sample(10)

       Make Colour  Odometer (KM)  Doors    Price
726     BMW  White       227845.0    5.0  11298.0
73      NaN    Red       227262.0    4.0  12001.0
100   Honda   Blue       146233.0    4.0  14202.0
375  Toyota  White       214493.0    4.0  12434.0
189     BMW  White       126441.0    5.0  39738.0
58   Toyota  White        97375.0    4.0  11479.0
943  Toyota   Blue       221076.0    4.0   8786.0
716  Toyota  White       124205.0    4.0   6917.0
680   Honda  Black        38327.0    4.0  23728.0
374  Toyota   Blue       198570.0    4.0  17284.0

In [23]:
counts = dataset["Make"].value_counts()
counts

Make
Toyota    379
Honda     292
Nissan    183
BMW        97
Name: count, dtype: int64

In [21]:
dataset["Make"].nunique()
threshold = 200

In [29]:
repl = counts[counts <= threshold].index #merge to NissanBMW beacuse it is less than 200

In [30]:
pd.get_dummies(dataset["Make"].replace(repl,'NissanBMW'))

     Honda  NissanBMW  Toyota
0     True      False   False
1    False       True   False
2     True      False   False
3    False      False    True
4    False       True   False
..     ...        ...     ...
995  False      False    True
996  False      False   False
997  False       True   False
998   True      False   False
999  False      False    True

[1000 rows x 3 columns]